language: objective-c
osx_image: xcode8
xcode_workspace: Example/HZExtend.xcworkspace
xcode_scheme: HZExtend-Example

before_install:
- env
- xcodebuild -version
- xcodebuild -showsdks
- xcpretty --version

script:
- set -o pipefail
- xcodebuild clean build -workspace Example/HZExtend.xcworkspace -scheme HZExtend-Example | xcpretty
